### ISSUE TITLE
Code doesn't build in godot master

### ISSUE THREAD

**Issue by jordo** [briansemrau/godot_box2d#12]
I can maintain a compatible 4.0 branch here:

https://github.com/winterpixelgames/godot_box2d/tree/4.0

**Comment by briansemrau** [comment]
If you'd like to maintain it, you're welcome to. I personally won't bother to maintain a 4.0 version until this module becomes a bit more stable.

**Comment by jordo** [comment]
sure thing.  I'll close this issue and just support it as I go.
