### ISSUE TITLE
Refactor and cleanup box2dworld_transforms once PR 44200 upstreamed in godot

### ISSUE THREAD

**Issue by jordo** [briansemrau/godot_box2d#22]
Once/if https://github.com/godotengine/godot/pull/44200 is up-streamed, cleanup box2dworld_transforms to sync with upstream fixes.

Currently nodes in-between space to body/fixture nodes will break with anything that doesn't inherit from Node2D (even though it should work with CanvasItem.

Backporting this to 3.2 can use the existing implementation, but it will be more flexible and have less undefined behaviour with CanvasItem nodes in 4.0

**Comment by jordo** [comment]
Well it seams that godot lead maintainer won't correct the way scene trees work upstream.  https://github.com/godotengine/godot/pull/44200 :(

This is probably going to lead to bunch of duplicated code and extra work to get global transforms to work properly (since apparently global transforms aren't even a thing that works correctly upstream).  

I may maintain a fork with the fix in a private repo, because I will need it for my networking module.  But I'll try and figure out some workaround that will be intuitive for users of this module and 'just work'.

**Comment by briansemrau** [comment]
I was catching up on that thread and I'm a bit curious what exactly the problem is. I agree that CanvasItem shouldn't break the transform chain in the tree, but Node? I'm a bit confused.

**Comment by jordo** [comment]
Ya, exactly.  I'm confused why they would want this experience as well.  They want to keep this experience:  https://youtu.be/WwOaTPljKzw over this one:  https://youtu.be/ala39TYA3h0

Below is what my scene tree looks like in my network game.  Box2dWorld at the root.  I have a pretty cool network game module that handle net stuff seamlessly.  Each network object in the screenshot below  (GameData, Playera1), has sprites and the Box2d body nodes etc.  And you know whats totally broken?  The transforms, because even though my net nodes inherit Node and don't contribte any transformation information the scene tree, they break global positions for any subnodes (which makes global position not really a thing).  

i.e. if you call "set_global_transform" on a Node2d, it doesn't actually do that...  It's the transform to the nearest non CanvasItem ancestor.  Which is totally unexpected and broken IMO,

![Screen Shot 2020-12-09 at 3 05 29 PM](https://user-images.githubusercontent.com/323868/101687349-fbf5dc80-3a2f-11eb-8705-9519367bbb74.png)

**Comment by jordo** [comment]
I have some workarounds we can use for this specific module, but it will mean my network sync module will not work with anything currently in upstream godot due to this limitation :(

**Comment by briansemrau** [comment]
Does your ~~gamedata~~ network relevant node(s) need to be the parent of everything beneath it? Instead of it "owning" everything in the tree _below_ it, could it own the _siblings_ in the tree? That way, you can instead have a Node2D named "Player" with the network controller as a child, next to all the relevant Player scene stuff.

**Comment by jordo** [comment]
It does.  It dynamically treats each gameobject directly under it as effectively the 'net state'.  I have no interest in going lower than 1 level, because a tree isn't an effective data structure for game state and it require me serializing a bunch of stuff that is totally uncessary.  But ya, the net game iterates the list of each gameobject's exported properties at runtime, and treats the aggregate of everything as the net state.    New game objects must be synced with a scene for instantiations and destructions.  The scene is the same, so the client and server execute the same code etc.

**Comment by jordo** [comment]
Here's what it looks like live:

![Screen Shot 2020-12-09 at 3 31 35 PM](https://user-images.githubusercontent.com/323868/101690985-a1f71600-3a33-11eb-8f88-b12b8f40cb79.png)

Sycnched across the net, and working correctly on this module now :D :D :D

**Comment by jordo** [comment]
![Screen Shot 2020-12-09 at 3 33 00 PM](https://user-images.githubusercontent.com/323868/101691115-d4087800-3a33-11eb-9c88-5ae56b6fd81c.png)

**Comment by jordo** [comment]
client game has some properties for auth tokens, and simulated lag and stuff for during development:

![Screen Shot 2020-12-09 at 3 33 41 PM](https://user-images.githubusercontent.com/323868/101691168-eb476580-3a33-11eb-8eaf-d6b4e94ea1c8.png)

**Comment by jordo** [comment]
Servers accept clients from whatever transport they want, enet for desktop/mobile, websocket for web.  Working really well so far.

**Comment by jordo** [comment]
anyways, all good.  I'm going to rewrite a few tranversal functions to do what we want now that I know I can't get something like this upstreamed.  Everything wrt this module will still work as designed.

**Comment by briansemrau** [comment]
Btw, I really like the way you're implementing your networking.

Yeah, I suppose discussion relevant to this module is cleared up. And I see your problem with your networking module.. Your design makes sense and I wish I had a good idea for a solution.

**Comment by jordo** [comment]
thx, haha :D ya, after too many years in VOIP and then a decade of doing netcode I suppose it has lead me be to be very opinionated on how to organize a client-prediected server-auth game.  (From dev environment to prod rollouts).   

Last two games I lead were 'golf blitz' and 'motorball'.  Both avail on iOS and Android for free if u wanna check em out :)

**Comment by jordo** [comment]
actually both those games are Box2D as well

**Comment by briansemrau** [comment]
hah i won my first game in motorball 😎 
nice stuff

**Comment by jordo** [comment]
this is as bout as clean as it will get in https://github.com/briansemrau/godot_box2d/pull/31
