### ISSUE TITLE
Box2dPhysicsNodes and fixtures should still work in sub-scenes.

### ISSUE THREAD

**Issue by jordo** [briansemrau/godot_box2d#26]
during porting of my project, I discovered that obviously physics bodies and fixtures need to be supported in sub-scenes.  i.e, the scene doesn't hold a world node, but is attached to another node which contains the world.    In the screenshot below GameData scene is included in another scene (which contains the box2d world). 

<img width="860" alt="Screen Shot 2020-12-08 at 8 36 18 PM" src="https://user-images.githubusercontent.com/323868/101566694-07e09080-3995-11eb-9c38-ed08b211ac03.png">

Going to investigate how to support this.

**Comment by briansemrau** [comment]
This seems to be the primary folly of using a node to represent the physics space. Godot doesn't have this issue because it uses a physics server singleton.

Having the world as a singleton may be the only way to resolve this. We can keep Box2DWorld as a node to create spaces other than the singleton.

I believe the code to look at is https://github.com/briansemrau/godot_box2d/blob/4.0/scene/2d/box2d_physics_body.cpp#L147 (as well as in Fixture and Joint)

**Comment by briansemrau** [comment]
My initial guess at a solution would be to make a modification to look for the singleton world in case one is not found in the scene tree.

**Comment by jordo** [comment]
I dunno, i'm not 100% sure about it.  I'm not a huge fan of singletons, and think there's a chance we don't need the world to do body and fixture setup.  

We could also default to having at least a global world available at the root, if you never add another one.  Going to investigate further, but you could be right.

**Comment by jordo** [comment]
IIRC The 'real root' in godot, is kinda above what you see above the scene tree (there's kinda one global root that loads scenes underneath it).  I think that's the case.  If that is the case, we can keep the 'World' lookup code the same (traverse up the tree until you find a world)

**Comment by jordo** [comment]
Alright, this should be working with https://github.com/briansemrau/godot_box2d/pull/31

**Comment by briansemrau** [comment]
Does this issue include the scope of running sub-scenes, even if just for testing? The current PR seems to make things better in the editor, but is limited to that.

**Comment by jordo** [comment]
sub-scenes should work, at least they do in my test project.  I've got the body nodes in subscenes below my world 

<img width="306" alt="Screen Shot 2020-12-09 at 10 04 30 PM" src="https://user-images.githubusercontent.com/323868/101720173-84916e80-3a6a-11eb-881a-d9c84e0f5ebc.png">

**Comment by jordo** [comment]
GameData looks like this:

<img width="854" alt="Screen Shot 2020-12-09 at 10 05 45 PM" src="https://user-images.githubusercontent.com/323868/101720242-b1de1c80-3a6a-11eb-9a1d-9e67420a19ce.png">

I still like the warnings, cause it still give the user a warning that they need to know what they are doing for this to work

**Comment by briansemrau** [comment]
If you run this sub-scene, however, it won't _work_, right? Because there is no b2world

**Comment by jordo** [comment]
ya, that's correct.  OK, i see what you are saying now.

**Comment by jordo** [comment]
So hmm, i feel like that is OK.  If users set things up like this they should know what they are doing.

**Comment by briansemrau** [comment]
At least the warnings make it very clear.
It's possible this will come up as an issue in the future, but it'll likely be handled when all the b2 stuff is put into a server. Topic for the future.

**Comment by briansemrau** [comment]
closing with #32 as followup to the discussion had
