### ISSUE TITLE
Should the b2 object lifecycle occur in the editor?

### ISSUE THREAD

**Issue by briansemrau** [briansemrau/godot_box2d#28]
This may be related to #26 in some respect.

Right now all body, fixture, and joint nodes create/destroy their b2objects within the editor. I don't think this is necessary and I'm not sure why it really needs to be done in the first place. (I think debug drawing might use it to some extent, but that can change)

I thought I had a stronger argument for this but I'm tired and can't think of one. Regardless, this is something that should have a clear decision: yes or no.

**Comment by jordo** [comment]
I'm not too sure what is best without taking a deeper look, but the less differences between the editor codepaths and runnable codepaths I think generally the better.  Less to test, and less potential bugs maybe?  The editor is effectively a working runnable environment anyways really, so maybe it shouldn't try to be too different.

**Comment by briansemrau** [comment]
So I think I remember why my initial intuition was to separate editor vs runtime behavior. Right now joint anchor configuration requires the existence of the relevant b2bodies. Trying to edit joint anchors in sub-scenes without a b2world (and hence no b2bodies) was impossible.

Though I totally agree with what you said: there shouldn't be unnecessary differences in codepaths. I will solve the problem I described above so that it isn't a continuing issue before #32 is implemented.
