### ISSUE TITLE
Node naming convention?

### ISSUE THREAD

**Issue by briansemrau** [briansemrau/godot_box2d#38]
When first working on this module, I didn't give much thought how nodes should be named. If it would be an improvement to change the naming scheme, it should happen as soon as possible.

Right now everything is prefixed with "Box2D".
**Pros:**
- It's very clear and obvious

**Cons:**
- It makes bulky names bulkier, such as Box2DPrismaticJoint and Box2DPhysicsBody.
- it takes 0.2 seconds longer to type than I'd like and is annoying for my left hand because I never use right-shift

Another idea is to use the prefix "B2".
**Pros:**
- it's shorter and more concise
- feels a bit more _sleek_ and _cool_ 😎 
- my left hand's quality of life improves by an amount that may or may not be within the margin of error for measuring "hand quality of life"

**Cons:**
- ?
- effort
- might be prone to confusion between, say, B2Joint and b2Joint

Other ideas are welcome.

I should note: Switching names should not be too difficult for existing projects. Doing a find/replace from "Box2D" to "B2"/whatever in each .tscn file should do the trick.

I'm serious enough about this issue that I'll make a name change if it's actually a good idea, but it's also unimportant enough that a singular thumb down might close this.

**Comment by jordo** [comment]
i'm fine with whatever, but the prefix is nice right now because i can regex on box2d* and find all box2d godot code.  b2* gives me all the thirdparty box2d src.    

Maybe B2D as the godot prefix?   Pro - it still has '2D' in the name which most other 2D nodes have as well.

**Comment by briansemrau** [comment]
I think I'll stick to keeping the naming as-is. While I genuinely dislike the bulk of "Box2D", I think it's the best option. There aren't many naming variations to choose from.
