### ISSUE TITLE
callbacks within a locked world

### ISSUE THREAD

**Issue by jordo** [briansemrau/godot_box2d#40]
hehe, I just hit this issue with my test project.  See callstack below:

![Screen Shot 2020-12-15 at 5 01 11 PM](https://user-images.githubusercontent.com/323868/102283122-5d69ef80-3ef7-11eb-9c3a-8e65f0c17696.png)

This is triggered from line 68 in the GDScript below:  (Basically I want to hide and disable this body when it hits another body).  
![Screen Shot 2020-12-15 at 5 03 26 PM](https://user-images.githubusercontent.com/323868/102283172-74104680-3ef7-11eb-8adc-724336a37b1d.png)

For right now, since `body_entered`,etc signals don't really need to happen inside the b2world step(), I'm just going to queue them up and emit them immediately after step().

This is going to be somewhat related to https://github.com/briansemrau/godot_box2d/issues/13 but in that case pre-solve will have to happen immediately.

**Comment by briansemrau** [comment]
Yeah those signals should not be emitted immediately during b2world.step

**Comment by briansemrau** [comment]
It wasn't totally clear to me when this was first brought up: Were you planning on fixing this issue as part of #13 or just bringing it up? Just trying to avoid duplicate work if I wanted to come around to fixing this.

**Comment by jordo** [comment]
I can merge my change as addresses the collision callbacks that are currently there.  

It doesn't catch it in the general cases (i still want to do explicit checks on IsLocked() and print warnings accordingly) but I have these callbacks queued up in another branch.  I'll just do a PR in a few min

**Comment by briansemrau** [comment]
Resolved by #41
