### ISSUE TITLE
Collision group_index overrides explicit collision exceptions

### ISSUE THREAD

**Issue by briansemrau** [briansemrau/godot_box2d#42]
I noticed this issue while working on code changes.

Code snippet pulled from box2d_world.cpp :
```cpp
bool Box2DWorld::ShouldCollide(b2Fixture *fixtureA, b2Fixture *fixtureB) {
	...
	if (filterA.groupIndex == filterB.groupIndex && filterA.groupIndex != 0) {
		return filterA.groupIndex > 0; // TODO fix this. Group index should not override explicit exclusions, calculated below.
	}
	...
	// Check for fixture exclusions
	...
}
```

The group_index calculation should only return if it's returning false.

Under the current behavior, if it returns true then body/fixture collision exclusions won't be able to disable collisions.

This will be fixed alongside my changes for #9

**Comment by jordo** [comment]
ah yes, nice catch.
