### ISSUE TITLE
Need to create node icon svg files

### ISSUE THREAD

**Issue by briansemrau** [briansemrau/godot_box2d#5]
Very few nodes have proper icons, and those that do are not finished. These .svg files need to be created.

Main uncertainty is what design would be best:
- Option 1:
Copy Godot's icons for nodes that exist, then add a small "b2" text (this is what is currently done)
- Option 2:
Like above, but instead of "b2" the icon color is a different color (I'm thinking purple)

Suggestions welcome. I'm not an experienced graphic designer.

**Comment by jordo** [comment]
+1 for keeping it blue, with a 'B2' somewhere
