### ISSUE TITLE
Cherry pick relevant commits from tankkings sdf branch

### ISSUE THREAD

**Issue by jordo** [briansemrau/godot_box2d#65]
We've probably got a few commits scattered in here that would be worthwhile cherry picking for 3.X.

https://github.com/winterpixelgames/godot_box2d/commits/game-tankkings

A lot of the commits on this branch are inter-mingled with a bunch of game specific tweaks and some box2d sdf fixture type, but there's probably some isolated commits that are worthwhile pulling in.  Example https://github.com/winterpixelgames/godot_box2d/commit/fd613e568c9b437a8799e9faf08585c473f4da07 for web export builds (which by default aren't compiled with rtti in godot)

**Comment by jordo** [comment]
short list for cherry-pick:

https://github.com/winterpixelgames/godot_box2d/commit/5e9c1d5b82e8ed1feb33e9871611b2f338045759
https://github.com/winterpixelgames/godot_box2d/commit/a0e93e0d4002f3dd3eb944224562d37e5786e3e0
https://github.com/winterpixelgames/godot_box2d/commit/fd613e568c9b437a8799e9faf08585c473f4da07
https://github.com/winterpixelgames/godot_box2d/commit/f8881fa26a01f38c7c91135fa5fdc5ddac61d8e7 and https://github.com/winterpixelgames/godot_box2d/commit/b37653a56c39b239bcd9518a5106581fcd3083ae

We moved to custom modules folder, so this path works better if you are using a custom modules folder:
https://github.com/winterpixelgames/godot_box2d/commit/76b443618f61a6dd115adf64b0b3a25cd55c0ec5

This one, i'm not sure but I think may be already integrated upstream:
https://github.com/winterpixelgames/godot_box2d/commit/3224b50de12cab758f48fdfda1910d2dba8865b7

**Comment by briansemrau** [comment]
Just want to note that the above-mentioned winterpixelgames@f8881fa and winterpixelgames@b37653a are on the same subject as #58. It makes sense to do those changes together.
(I'm dipping my toes in server-side rollback and may tackle that issue soon.)

**Comment by jordo** [comment]
Expose position and velocity on b2world_step

https://github.com/winterpixelgames/godot_box2d/commit/410d0f9f0a375a86d026b0554bc3284a94c89c06

**Comment by briansemrau** [comment]
FYI I'm working on cherry picking some of this stuff into https://github.com/briansemrau/godot_box2d/tree/bugfix/various-fixes

**Comment by briansemrau** [comment]
I'm going to close this. Feel free to reopen it if more cherrypicks come up.
