### ISSUE TITLE
Missing world query functions

### ISSUE THREAD

**Issue by briansemrau** [briansemrau/godot_box2d#9]
Box2D has the following functions ([seen here](https://docs.godotengine.org/en/3.2/classes/class_physics2ddirectspacestate.html)):
- `b2World.QueryAABB` (returns all fixtures who's AABB intersects a given AABB)
- `b2World.RayCast`

Godot has the functions ([seen here](https://box2d.org/documentation/classb2_world.html#ad169fae775be1e1f16386f7587786fa8)):
- `Physics2DDirectSpaceState.cast_motion`
- `Physics2DDirectSpaceState.collide_shape`
- `Physics2DDirectSpaceState.intersect_point`
- `Physics2DDirectSpaceState.intersect_ray`
- `Physics2DDirectSpaceState.intersect_shape`

These all provide an important functionality that this module is missing. This list may not be complete.

The Box2D functions are easy enough to provide, but achieving feature-parity with Godot physics requires more work. All `intersect_x` functions require working with the Box2D collision module. However, `cast_motion` is most difficult. I'm not sure the best approach, but Box2D does not have any advertised way to handle continuous collision queries.

**Comment by jordo** [comment]
b2_collision.h has b2TestOverlap that can be used directly, for something like collide_shape.

**Comment by jordo** [comment]
does cast_motion even consider time?  There is no delta T in any argument.  Could be implemented via raycast per vertex?

**Comment by jordo** [comment]
also, note there is two b2TestOverlaps   Once for just AABBs and one for actual shapes.

**Comment by jordo** [comment]
Looking through how cast_motion is implemented in the existing physics systems, I think we can use the b2d collision module directly to implement it.

**Comment by briansemrau** [comment]
Should the querying API take inputs in global space or Box2DWorld local space? For my usage of this module it doesn't make a difference, but I'm not sure if this will have any unexpected behavior for how you use Box2DWorld @jordo

**Comment by jordo** [comment]
I would think the Box2DWorld space, which would be the same space as body & fixture transforms.

**Comment by briansemrau** [comment]
The documentation for Physics2DDirectSpaceState `collide_shape` is ambiguous and I'm not sure it's worth implementing. I think it might be similar to getting manifold points of a collision.

Also, there's another function `get_rest_info` that does _not_ sound like what it does, which the docs say is to return the closest colliding shape. I won't bother implementing this either, since it seems to be neglected (judging by the naming).
